name: Deploy to S3

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Sync build to S3
        run: aws s3 sync ./dist s3://truman-socialmedia-test --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E2L2XKTLIG48X2 --paths "/*"
